package com.example.ziva.util

enum class AppLanguage(val code: String, val displayName: String, val nativeName: String) {
    ENGLISH("en", "English", "English"),
    HINDI("hi", "Hindi", "हिंदी"),
    SPANISH("es", "Spanish", "Español"),
    BENGALI("bn", "Bengali", "বাংলা"),
    MARATHI("mr", "Marathi", "मराठी")
}

object LanguageManager {
    private val translations = mapOf(
        AppLanguage.ENGLISH to mapOf(
            "app_title" to "ZIVA Assistance",
            "sos_tab" to "SOS Alert",
            "resources_tab" to "Resources",
            "track_tab" to "Track Help",
            "profile_tab" to "Relay & Sync",
            "trigger_sos" to "HOLD FOR SOS",
            "tap_instruction" to "Tap or hold for instant emergency broadcast",
            "auto_capture" to "Auto-Capturing GPS, Battery & Connectivity",
            "silence_detected" to "Silent/DND mode detected. Escalate sound?",
            "confirm_sound" to "Sound Loud Alarm",
            "keep_silent" to "Keep Silent",
            "battery_warning" to "Low Battery (<=15%). Power-save BLE mode active.",
            "emergency_type" to "Emergency Type",
            "voice_note" to "Add Voice / Text Note",
            "request_id_label" to "PERSISTENT REQUEST ID",
            "status_queued" to "QUEUED LOCALLY",
            "status_ble" to "RELAYED VIA BLE HOPS",
            "status_synced" to "SYNCED TO CLOUD",
            "eta_label" to "Estimated Arrival",
            "verified_resources" to "Verified Nearby Resources",
            "freshness_fresh" to "Fresh (<=30 min)",
            "freshness_stale" to "Stale (>30 min ago)",
            "available_volunteers" to "Nearby Volunteers",
            "force_sync" to "Sync Queue to Cloud",
            "mesh_status" to "BLE Multi-Hop Mesh",
            "relay_nodes" to "Active Relay Peers",
            "packets_forwarded" to "Packets Relayed",
            "dedup_rate" to "Duplicate Drop Rate",
            "call_volunteer" to "Call Responder",
            "request_help" to "Request Assigned Help"
        ),
        AppLanguage.HINDI to mapOf(
            "app_title" to "ज़िवा आपदा सहायता",
            "sos_tab" to "आपातकालीन",
            "resources_tab" to "संसाधन",
            "track_tab" to "मदद ट्रैक करें",
            "profile_tab" to "रिले व सिंक",
            "trigger_sos" to "आपातकालीन SOS",
            "tap_instruction" to "तत्काल सहायता प्रसारण के लिए दबाएं",
            "auto_capture" to "जीपीएस, बैटरी और नेटवर्क स्वतः दर्ज",
            "silence_detected" to "शांत मोड मिला। क्या तेज़ अलार्म बजाएं?",
            "confirm_sound" to "तेज़ आवाज़ बजाएं",
            "keep_silent" to "शांत रखें",
            "battery_warning" to "कम बैटरी (<=15%)। बिजली बचत सक्रिय।",
            "emergency_type" to "आपदा प्रकार",
            "voice_note" to "आवाज़ या संदेश जोड़ें",
            "request_id_label" to "अनुरोध पहचान संख्या",
            "status_queued" to "स्थानीय रूप से कतारबद्ध",
            "status_ble" to "ब्लूटूथ मेश द्वारा रिले",
            "status_synced" to "क्लाउड पर सुरक्षित",
            "eta_label" to "पहुंचने का अनुमानित समय",
            "verified_resources" to "सत्यापित नजदीकी संसाधन",
            "freshness_fresh" to "ताज़ा (<=30 मिनट)",
            "freshness_stale" to "पुराना (>30 मिनट पहले)",
            "available_volunteers" to "उपलब्ध स्वयंसेवक",
            "force_sync" to "क्लाउड से सिंक करें",
            "mesh_status" to "बीएलई मल्टी-हॉप मेश",
            "relay_nodes" to "सक्रिय रिले नोड्स",
            "packets_forwarded" to "रिले किए गए पैकेट",
            "dedup_rate" to "डुप्लिकेट दर",
            "call_volunteer" to "कॉल करें",
            "request_help" to "मदद मांगें"
        ),
        AppLanguage.SPANISH to mapOf(
            "app_title" to "ZIVA Asistencia",
            "sos_tab" to "Alerta SOS",
            "resources_tab" to "Recursos",
            "track_tab" to "Rastrear Ayuda",
            "profile_tab" to "Relé y Sinc",
            "trigger_sos" to "MANTENER PARA SOS",
            "tap_instruction" to "Toque para transmisión de emergencia inmediata",
            "auto_capture" to "Captura automática de GPS, batería y red",
            "silence_detected" to "Modo silencio detectado. ¿Escalar alarma?",
            "confirm_sound" to "Sonar Alarma Fuerte",
            "keep_silent" to "Mantener en Silencio",
            "battery_warning" to "Batería baja (<=15%). Modo BLE de bajo consumo.",
            "emergency_type" to "Tipo de Emergencia",
            "voice_note" to "Nota de voz / texto",
            "request_id_label" to "ID DE SOLICITUD PERSISTENTE",
            "status_queued" to "EN COLA LOCAL",
            "status_ble" to "RETRANSMITIDO VÍA BLE",
            "status_synced" to "SINCRONIZADO EN NUBE",
            "eta_label" to "Tiempo Estimado de Llegada",
            "verified_resources" to "Recursos Cercanos Verificados",
            "freshness_fresh" to "Reciente (<=30 min)",
            "freshness_stale" to "Desactualizado (>30 min)",
            "available_volunteers" to "Voluntarios Cercanos",
            "force_sync" to "Sincronizar a la Nube",
            "mesh_status" to "Malla Multi-salto BLE",
            "relay_nodes" to "Nodos de Relé Activos",
            "packets_forwarded" to "Paquetes Retransmitidos",
            "dedup_rate" to "Tasa de Descarte Duplicados",
            "call_volunteer" to "Llamar Respondedor",
            "request_help" to "Solicitar Asistencia"
        ),
        AppLanguage.BENGALI to mapOf(
            "app_title" to "জিভা দুর্যোগ সহায়তা",
            "sos_tab" to "জরুরি সংকেত",
            "resources_tab" to "সম্পদসমূহ",
            "track_tab" to "সাহায্য ট্র্যাক",
            "profile_tab" to "রিলে ও সিঙ্ক",
            "trigger_sos" to "জরুরি SOS পাঠান",
            "tap_instruction" to "তাত্ক্ষণিক সাহায্যের জন্য ট্যাপ করুন",
            "auto_capture" to "জিপিএস, ব্যাটারি ও সংযোগ চিহ্নিত",
            "silence_detected" to "নীরব মোড সক্রিয়। শব্দ কি বাড়ানো হবে?",
            "confirm_sound" to "উচ্চ শব্দ বাজান",
            "keep_silent" to "নীরব রাখুন",
            "battery_warning" to "কম ব্যাটারি (<=১৫%)। শক্তি সঞ্চয় মোড চালু।",
            "emergency_type" to "জরুরি অবস্থা ধরন",
            "voice_note" to "ভয়েস বা টেক্সট যোগ করুন",
            "request_id_label" to "অনুরোধ আইডি",
            "status_queued" to "স্থানীয়ভাবে জমা আছে",
            "status_ble" to "বিএলই রিলে দ্বারা প্রেরিত",
            "status_synced" to "ক্লাউডে সংরক্ষিত",
            "eta_label" to "পৌঁছানোর আনুমানিক সময়",
            "verified_resources" to "যাচাইকৃত কাছাকাছি সম্পদ",
            "freshness_fresh" to "তাজা (<=৩০ মিনিট)",
            "freshness_stale" to "পুরনো (>৩০ মিনিট আগে)",
            "available_volunteers" to "কাছাকাছি স্বেচ্ছাসেবক",
            "force_sync" to "ক্লাউড সিঙ্ক করুন",
            "mesh_status" to "বিএলই মাল্টি-হপ মেশ",
            "relay_nodes" to "সক্রিয় নোডসমূহ",
            "packets_forwarded" to "রিলে করা প্যাকেট",
            "dedup_rate" to "ডুপ্লিকেট বাতিলের হার",
            "call_volunteer" to "কল করুন",
            "request_help" to "সাহায্য চান"
        ),
        AppLanguage.MARATHI to mapOf(
            "app_title" to "झिवा आपत्ती सहाय्य",
            "sos_tab" to "तातडीचा SOS",
            "resources_tab" to "साधनसामग्री",
            "track_tab" to "मदत ट्रॅक करा",
            "profile_tab" to "रिले व सिंक",
            "trigger_sos" to "तातडीचा SOS पाठवा",
            "tap_instruction" to "त्वरित मदतीसाठी दाबा",
            "auto_capture" to "जीपीएस, बॅटरी व नेटवर्क नोंदवले",
            "silence_detected" to "सायलेंट मोड आहे. अलार्म वाजवायचा का?",
            "confirm_sound" to "मोठा आवाज करा",
            "keep_silent" to "शांत ठेवा",
            "battery_warning" to "कमी बॅटरी (<=१५%). पॉवर सेव्हर मोड सुरू.",
            "emergency_type" to "आपत्तीचा प्रकार",
            "voice_note" to "आवाज किंवा मजकूर जोडा",
            "request_id_label" to "विनंती ओळख क्रमांक",
            "status_queued" to "स्थानिकरित्या सुरक्षित",
            "status_ble" to "ब्लूटूथ मेशने पाठवले",
            "status_synced" to "क्लाउडवर सिंक झाले",
            "eta_label" to "पोहोचण्याची अंदाजे वेळ",
            "verified_resources" to "तपासलेली मदत केंद्रे",
            "freshness_fresh" to "ताजे (<=३० मिनिटे)",
            "freshness_stale" to "जुने (>३० मिनिटे जुने)",
            "available_volunteers" to "जवळचे स्वयंसेवक",
            "force_sync" to "क्लाउडवर सिंक करा",
            "mesh_status" to "बीएलई मल्टी-हॉप मेश",
            "relay_nodes" to "सक्रिय रिले नोड्स",
            "packets_forwarded" to "फॉरवर्ड केलेले पॅकेट्स",
            "dedup_rate" to "डुप्लिकेट वगळण्याचे प्रमाण",
            "call_volunteer" to "कॉल करा",
            "request_help" to "मदतीची विनंती करा"
        )
    )

    fun getString(key: String, language: AppLanguage): String {
        return translations[language]?.get(key)
            ?: translations[AppLanguage.ENGLISH]?.get(key)
            ?: key
    }
}
